### ISSUE TITLE
Need help to create embeddings

### ISSUE THREAD

**Issue by SamraMehboob** [JetBrains-Research/embeddings-for-trees#14]
Hi there,
Thank you for this amazing work. I'm trying to create embeddings for ASTs. I generated ASTs for source code using astminer tool. Then I put that file with train.jsonl  name inside this project. But I'm facing following error, can you please help with it. I'm a beginner. I'll be really thankful.

![Screenshot (22)](https://user-images.githubusercontent.com/60770335/151450985-07af524a-ea83-483a-9057-645fe1c5e69b.png)

**Comment by SpirinEgor** [comment]
Hi!
Thank you for the feedback!

It seems that there is a little out of sync between `astminer` and this lib. In `astminer` AST stores in JSON under `ast` key and this library tries to read by key `tree`. You can change this behavior by changing the value [here](https://github.com/JetBrains-Research/embeddings-for-trees/blob/master/embeddings_for_trees/utils/common.py#L7). Just set `AST = "ast"`.

**Comment by SamraMehboob** [comment]
Hi
Thank you for help, its resolved. 
But another same error appeared. 
![nodeTypeError](https://user-images.githubusercontent.com/60770335/151797180-0a376220-9ee3-4ac4-a7d8-2b27e9d7cf35.png)

I tried to change NODE = "nodeType" to NODE= "typeLabel" but it didn't work. 
I guess it is due to compatibility issue between astminer output and this lib. 
There are 2 to 3 ways to create AST using astminer, can you let me know which format this lib is using or help me with above error. 
 Thanks.

**Comment by SpirinEgor** [comment]
Hi!

Using `typeLabel` should be ok.
You should use `json AST` storage in `astminer`:
```
storage:
  name: json AST
```

Could you provide some `astminer` output examples?

**Comment by SamraMehboob** [comment]
I created ASTs using Antrl provided by astminer.
Here is output example.

{"label":"1542.java","ast":[{"token":"<E>","typeLabel":"compilationUnit","children":[1,2]},{"token":"date|time|parser","typeLabel":"IDENTIFIER","children":[]},{"token":"parser","typeLabel":"IDENTIFIER","children":[]}]}

**Comment by SpirinEgor** [comment]
Oh, it seems I found a bug in vocabulary implementation. Instead of using `NODE` value from `common.py`, it uses internal value:
https://github.com/JetBrains-Research/embeddings-for-trees/blob/master/embeddings_for_trees/data/vocabulary.py#L14
Try to change this `NODE` to `typeLabel`

**Comment by SamraMehboob** [comment]
Ok thank you. I'll try updating it.

**Comment by SamraMehboob** [comment]
I updated it then I get error in jsonl_dataset.py. It seems **NODE** value needs to be changed at some other place as well.
![json1_datasetError](https://user-images.githubusercontent.com/60770335/151963773-7a1d3799-3480-4090-9e84-f91b3d76210b.png)

**Comment by SamraMehboob** [comment]
I changed NODE to typeLabel in common.py as well. It worked now.

https://github.com/JetBrains-Research/embeddings-for-trees/blob/master/embeddings_for_trees/utils/common.py

Thank you for support.

**Comment by SpirinEgor** [comment]
Nice to hear that it works!
I will update the codebase to make it easier for future usage.

If you have any other questions please feel free to open new issues.
